orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  node-test:
    executor:
      name: node/default
      #tag: '13.14'
    steps:
      #- run:
      #    command: while true; do echo $(date +"%T") $(cat /sys/fs/cgroup/cpuacct/cpuacct.usage) >> /tmp/cpu_util.log && sleep 1; done
      #    background: true
      - run:
          #I don't think this actually shows anything useful
          command: |
            sudo apt update && sudo apt install bc -y
            echo Timestamp \| CPU Util Percentage >> /tmp/cpu_util_pct.log
            while true; do
              tstart=$(date +%s%N)
              cstart=$(cat /sys/fs/cgroup/cpu/cpuacct.usage)
              sleep 1
              tstop=$(date +%s%N)
              cstop=$(cat /sys/fs/cgroup/cpu/cpuacct.usage)
              echo $(date +"%T") \| $( echo "($cstop - $cstart) / ($tstop - $tstart) * 100" | bc ) >> /tmp/cpu_util_pct.log
            done
          background: true
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          name: Usage stats
          command: |
            echo Memory max usage: $(expr $(cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes) / 1000000) MB | tee /tmp/max_mem_util.log    
            echo 
            cat /tmp/cpu_util_pct.log
          when: always
      - store_artifacts:
          path: /tmp/cpu_util_pct.log
      - store_artifacts:
          path: /tmp/max_mem_util.log    

workflows:
  app-tests:
    jobs:
      - node-test