orbs:
  node: circleci/node@4.0.0
  docker-cpu-profiling: mkly/docker-cpu-profiling@0.2.1

version: 2.1

jobs:
  node-test:
    executor:
      name: node/default
      #tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          name: Usage stats
          command: |
            echo Memory max usage: $(expr $(cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes) / 1000000) MB  
          when: always 

workflows:
  app-tests:
    jobs:
      - node-test:
          pre-steps:
            - docker-cpu-profiling/profile