orbs:
  aws-ecs: circleci/aws-ecs@1.4.0
  terraform: circleci/terraform@1.2.0
  aws-ecr: circleci/aws-ecr@6.15.2
  node: circleci/node@4.0.0

version: 2.1

jobs:
  static-analysis:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - run: |
          npm install eslint eslint-plugin-react 
          node_modules/eslint/bin/eslint.js ./src/
        #TODO configure eslint
  terraform-linting:
    docker:
      - image: cimg/base:2021.01 
    steps:
      - checkout
      - terraform/install:  
          terraform_version: 0.14.5
      - terraform/fmt:  
          path: ./tf/ecr
      - terraform/validate:  
          path: ./tf/ecr
      - terraform/fmt:  
          path: ./tf/route53
      - terraform/validate:  
          path: ./tf/route53
  terraform-check-ecr-and-dns:
    docker:
      - image: cimg/base:2021.01 
    steps:
      - checkout
      - terraform/install:  
          terraform_version: 0.14.5
      - terraform/init:
          path: ./tf/ecr
      - terraform/apply:
          path: ./tf/ecr
          var: 'aws_resource_name_prefix=${AWS_RESOURCE_NAME_PREFIX}'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - terraform-linting:
          context: node-demo
      - node/test
      - static-analysis
      - terraform-check-ecr-and-dns:
          context: node-demo
          requires:
            - terraform-linting
      - manual-approval:
          type: approval
          requires:
            - node/test
            - static-analysis
            - terraform-check-ecr-and-dns
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}-ecr"
          tag: "${CIRCLE_SHA1}"
          context: node-demo
          create-repo: false
          requires:
            - manual-approval
      - aws-ecs/deploy-service-update:
          context: node-demo
          requires:
            - aws-ecr/build-and-push-image 
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"



