orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  node-test:
    executor:
      name: node/default
      #tag: '13.14'
    steps:
      #- run:
      #    command: while true; do echo $(date +"%T") $(cat /sys/fs/cgroup/cpuacct/cpuacct.usage) >> /tmp/cpu_util.log && sleep 1; done
      #    background: true
      - run:
          command: |
            while true; do
              cgroup=$(awk -F: '$2 == "cpu,cpuacct" { print $3 }' /proc/self/cgroup)
              tstart=$(date +%s%N)
              cstart=$(cat /sys/fs/cgroup/cpu/$cgroup/cpuacct.usage)
              sleep 1
              tstop=$(date +%s%N)
              cstop=$(cat /sys/fs/cgroup/cpu/$cgroup/cpuacct.usage)
              echo $(date +"%T") $(($cstop - $cstart) / ($tstop - $tstart) * 100)) >> /tmp/cpu_util_pct.log
            done
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes >> /tmp/max_mem_util.log
          when: always
      - store_artifacts:
          path: /tmp/cpu_util.log
      - store_artifacts:
          path: /tmp/max_mem_util.log    

workflows:
  app-tests:
    jobs:
      - node-test