orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  node-test:
    executor:
      name: node/default
      #tag: '13.14'
    steps:
      - run:
          command: while true; do echo $(date +"%T") $(cat /sys/fs/cgroup/cpuacct/cpuacct.usage) >> /tmp/cpu_util.log && sleep 1; done
          background: true
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes >> /tmp/max_mem_util.log
          when: always
      - store_artifacts:
          path: /tmp/cpu_util.log
      - store_artifacts:
          path: /tmp/max_mem_util.log    

workflows:
  app-tests:
    jobs:
      - node-test